In [1]:
import numpy as np
import pandas as pd

In [88]:
df = pd.read_csv('name.csv')

In [89]:
df.head()

Names  Label
0        Om      1
1     Ajay       1
2    Vijay       1
3     Aman       1
4  Shubham       1

In [90]:
names = df['Names']

In [91]:
# ascii_names = []
# maxlen = 20
# for name in names:
#     arr = []
#     for char in name:
#         if char.isupper():
#             arr.append((ord(char)+32))
#         elif char.islower():
#             arr.append(ord(char))
#         else:
#             continue
#     length = 20 - len(arr)
#     for _ in range(length):
#         arr.append(0)
#     arr = np.array(arr)
#     if len(arr)>20:
#         print (name)
#         continue
#     arr = arr.reshape(20,1)
# #     print (arr.shape)
#     ascii_names.append(arr)
# ascii_names = np.array(ascii_names)       
# # print (ascii_names)

In [92]:
def wrd_converter(name):
    maxlen = 20
    arr = []
    for i,char in enumerate(name):
        if i>=maxlen:
            break
        if char.isupper():
            arr.append((ord(char)+32)/122)
        elif char.islower():
            arr.append(ord(char)/122)
        else:
            continue
    length = maxlen - len(arr)
    for _ in range(length):
        arr.append(0)
    arr = np.array(arr)
    arr = arr.reshape(20,1)
    return arr
    

In [93]:
ascii_names = []
for name in names:
    arr = wrd_converter(name)
    ascii_names.append(arr)
ascii_names = np.array(ascii_names)       
print (ascii_names)

[[[0.90983607]
  [0.89344262]
  [0.        ]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.79508197]
  [0.86885246]
  [0.79508197]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[0.96721311]
  [0.86065574]
  [0.86885246]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 ...

 [[1.        ]
  [0.95901639]
  [0.86065574]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[1.        ]
  [0.95901639]
  [0.86065574]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]

 [[1.        ]
  [0.95901639]
  [0.86065574]
  ...
  [0.        ]
  [0.        ]
  [0.        ]]]


In [94]:
NewDf = df.copy()
# NewDf['Names'] = ascii_names
# NewDf.head()

In [95]:
X_train = ascii_names
Y_train = np.array(NewDf['Label'])

In [96]:
X_train.shape

(768, 20, 1)

In [97]:
Y_train = Y_train.reshape(768 ,1)
Y_train.shape

(768, 1)

In [98]:
from sklearn.model_selection import train_test_split

In [99]:
X_train =  np.array(ascii_names)
Y_train = np.array(NewDf['Label'])
train_X,test_X,train_Y,test_Y = train_test_split(X_train, Y_train, test_size=0.33, random_state=42)

# X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1],1))
# test_X  = np.reshape(X_test, (X_test.shape[0], X_test.shape[1],1))
# y_train = y_train.reshape(1563,1)
# Y_test  =Y_test.reshape(516 ,1)

print (train_X.shape)
print (test_X.shape)
print (train_Y.shape)
print (test_Y.shape)

(514, 20, 1)
(254, 20, 1)
(514,)
(254,)


In [100]:
from keras.layers.core import Dense, Activation, Dropout
from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM

In [120]:
model = Sequential()
model.add(LSTM(512, return_sequences=True, input_shape=(20,1)))
model.add(Dropout(0.1))
model.add(LSTM(256, return_sequences=False))
model.add(Dropout(0.2))
model.add(Dense(128))
model.add(Dense(32))
model.add(Dense(8))
model.add(Dense(2))
model.add(Activation('softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

In [121]:
batch_size=10
model.fit(train_X, train_Y, batch_size=batch_size, nb_epoch=10, validation_data=(test_X, test_Y))

d:\conda\envs\r-tensorflow\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  


Train on 514 samples, validate on 254 samples
Epoch 1/10
514/514 [==============================] - 9s 17ms/step - loss: 0.6917 - accuracy: 0.5953 - val_loss: 0.6799 - val_accuracy: 0.5748
Epoch 2/10
514/514 [==============================] - 8s 15ms/step - loss: 0.6765 - accuracy: 0.5992 - val_loss: 0.6796 - val_accuracy: 0.5748
Epoch 3/10
514/514 [==============================] - 7s 14ms/step - loss: 0.6742 - accuracy: 0.5992 - val_loss: 0.6803 - val_accuracy: 0.5748
Epoch 4/10
514/514 [==============================] - 8s 16ms/step - loss: 0.6756 - accuracy: 0.5992 - val_loss: 0.6826 - val_accuracy: 0.5748
Epoch 5/10
514/514 [==============================] - 8s 16ms/step - loss: 0.6767 - accuracy: 0.5992 - val_loss: 0.6861 - val_accuracy: 0.5748
Epoch 6/10
514/514 [==============================] - 8s 16ms/step - loss: 0.6759 - accuracy: 0.5992 - val_loss: 0.6812 - val_accuracy: 0.5748
Epoch 7/10
514/514 [==============================] - 8s 16ms/step - loss: 0.6767 - accuracy: 0.

In [117]:
def predict(name):
    arr = wrd_converter(name)
    arr = np.array(arr)
    arr = arr.reshape(1,arr.shape[0],arr.shape[1])
    pred=model.predict(arr)
    
    return pred

In [107]:
predict('xxxxy')

array([[0.42733112, 0.57266885]], dtype=float32)